const INITIAL_MOVIES = [
  {
    id: "mad-max-fury-road",
    title: "Mad Max: Fury Road",
    year: 2015,
    type: "movie",
    genres: ["action", "sci-fi"],
    rating: 8.1,
    personalRating: 9.5,
    director: "George Miller",
    cast: "Tom Hardy, Charlize Theron, Nicholas Hoult",
    coverUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
    review: "An absolute masterclass in kinetic filmmaking. The pacing is relentless, the practical effects are jaw-dropping, and the feminist undertones are beautifully integrated. Furiosa is one of the greatest cinematic icons of this century.",
    linkUrl: "https://www.youtube.com/watch?v=hEJnMQG9ev8"
  },
  {
    id: "the-conjuring",
    title: "The Conjuring",
    year: 2013,
    type: "movie",
    genres: ["horror", "mystery"],
    rating: 7.5,
    personalRating: 8.8,
    director: "James Wan",
    cast: "Vera Farmiga, Patrick Wilson, Lili Taylor",
    coverUrl: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=600&auto=format&fit=crop&q=80",
    review: "James Wan revitalized the classic haunted house genre with incredible atmosphere, suspense, and emotional grounding. The cinematography is outstandingly creepy, relying on camera movement and shadows rather than cheap jump scares.",
    linkUrl: "https://www.youtube.com/watch?v=k10ETZ41q5o"
  },
  {
    id: "get-out",
    title: "Get Out",
    year: 2017,
    type: "movie",
    genres: ["horror", "thriller", "mystery"],
    rating: 7.8,
    personalRating: 9.2,
    director: "Jordan Peele",
    cast: "Daniel Kaluuya, Allison Williams, Bradley Whitford",
    coverUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=600&auto=format&fit=crop&q=80",
    review: "A brilliant blend of social satire and psychological horror. Jordan Peele's directorial debut is airtight, with every detail serving a dual purpose. It's smart, unsettling, and incredibly rewatchable.",
    linkUrl: "https://www.youtube.com/watch?v=sRfnebTDP40"
  },
  {
    id: "inception",
    title: "Inception",
    year: 2010,
    type: "movie",
    genres: ["thriller", "action", "sci-fi"],
    rating: 8.8,
    personalRating: 9.6,
    director: "Christopher Nolan",
    cast: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy",
    coverUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80",
    review: "An ambitious heist movie set inside the subconscious. Nolan combines complex high-concept storytelling with spectacular action and emotional stakes. Hans Zimmer's score elevates this to legendary status.",
    linkUrl: "https://www.youtube.com/watch?v=YoHD9XEInc0"
  },
  {
    id: "shutter-island",
    title: "Shutter Island",
    year: 2010,
    type: "movie",
    genres: ["thriller", "mystery"],
    rating: 8.2,
    personalRating: 9.0,
    director: "Martin Scorsese",
    cast: "Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley",
    coverUrl: "https://images.unsplash.com/photo-1533240332313-0db49b439ad3?w=600&auto=format&fit=crop&q=80",
    review: "A beautifully crafted neo-noir psychological thriller. Scorsese builds a suffocating sense of dread and paranoia on the isolated island. The final twist forces you to re-evaluate the entire movie on a second viewing.",
    linkUrl: "https://www.youtube.com/watch?v=5iaYLCip5Qk"
  },
  {
    id: "1917",
    title: "1917",
    year: 2019,
    type: "movie",
    genres: ["war", "drama", "action"],
    rating: 8.2,
    personalRating: 9.3,
    director: "Sam Mendes",
    cast: "George MacKay, Dean-Charles Chapman, Richard Madden",
    coverUrl: "https://images.unsplash.com/photo-1473163928189-364b2c4e1135?w=600&auto=format&fit=crop&q=80",
    review: "Roger Deakins' 'single-shot' cinematography is not just a gimmick; it creates an immersive, claustrophobic journey through the hell of WWI. The sound design and musical score are deeply emotional and intense.",
    linkUrl: "https://www.youtube.com/watch?v=gZjQROMAh_s"
  },
  {
    id: "saving-private-ryan",
    title: "Saving Private Ryan",
    year: 1998,
    type: "movie",
    genres: ["war", "drama"],
    rating: 8.6,
    personalRating: 9.5,
    director: "Steven Spielberg",
    cast: "Tom Hanks, Matt Damon, Tom Sizemore",
    coverUrl: "https://images.unsplash.com/photo-1547483238-f400e65ccd56?w=600&auto=format&fit=crop&q=80",
    review: "The opening 20 minutes on Omaha Beach are some of the most harrowing, visceral, and realistic depictions of warfare ever put to film. Beyond the action, it's a poignant exploration of the cost of brotherhood and duty.",
    linkUrl: "https://www.youtube.com/watch?v=zwhP5b4tD6g"
  },
  {
    id: "breaking-bad",
    title: "Breaking Bad",
    year: 2008,
    type: "series",
    genres: ["thriller", "drama"],
    rating: 9.5,
    personalRating: 9.9,
    director: "Vince Gilligan",
    cast: "Bryan Cranston, Aaron Paul, Anna Gunn",
    coverUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
    review: "Arguably the most perfectly paced television series in history. The character arc of Walter White transforming from a mild-mannered chemistry teacher to a ruthless drug lord is tragic, terrifying, and deeply compelling.",
    linkUrl: "https://www.youtube.com/watch?v=HhesaQXLuRY"
  },
  {
    id: "chernobyl",
    title: "Chernobyl",
    year: 2019,
    type: "series",
    genres: ["drama", "thriller", "history"],
    rating: 9.3,
    personalRating: 9.7,
    director: "Craig Mazin",
    cast: "Jared Harris, Stellan Skarsgård, Emily Watson",
    coverUrl: "https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?w=600&auto=format&fit=crop&q=80",
    review: "A chilling, masterfully written miniseries that treats the nuclear disaster as a horror film of lies and bureaucracy. The tension is palpable even when characters are just sitting in committee rooms discussing physics.",
    linkUrl: "https://www.youtube.com/watch?v=s9APLXM9Ei8"
  },
  {
    id: "stranger-things",
    title: "Stranger Things",
    year: 2016,
    type: "series",
    genres: ["horror", "sci-fi", "drama"],
    rating: 8.7,
    personalRating: 9.0,
    director: "The Duffer Brothers",
    cast: "Millie Bobby Brown, Winona Ryder, David Harbour",
    coverUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
    review: "A wonderful love letter to 80s cinema. The series blends Steven Spielberg-like childhood wonder with Stephen King-esque horror. The cast chemistry, retro synth soundtrack, and creature designs are absolute standouts.",
    linkUrl: "https://www.youtube.com/watch?v=b9EkMc79ZSU"
  }
];
